export const icTechs = [
    {
        title: 'Figma',
        alt: 'figma',
        url: 'assets/logo_figma.svg',
    },
    {
        title: 'Visual Studio Code',
        alt: 'vscode',
        url: 'assets/logo_vscode.svg',
    },
    {
        title: 'HTML',
        alt: 'html',
        url: 'assets/logo_html.svg',
    },
    {
        title: 'CSS',
        alt: 'css',
        url: 'assets/logo_css.svg',
    },
    {
        title: 'Java Script',
        alt: 'javascipt',
        url: 'assets/logo_javascript.svg',
    },
    {
        title: 'Bootstrap',
        alt: 'bootstrap',
        url: 'assets/logo_bootstrap.svg',
    },
    {
        title: 'JQuery',
        alt: 'jquery',
        url: 'assets/logo_jquery.svg',
    },
];

export const dataModals = [
    {
        title: 'HTML/CSS',
        alt: 'htmlcss',
        url: 'assets/kelas1.png',
        link: 'class/1/',
        target: '_blank',
        rel: 'noopener noreferrer',
        content: 'Landing Page Osiris',
    },
    {
        title: 'Bootstrap 1',
        alt: 'bootstrap1',
        url: 'assets/kelas-21.png',
        link: 'class/2/1/',
        target: '_blank',
        rel: 'noopener noreferrer',
        content: 'Landing Page Bootstrap 4',
    },
    {
        title: 'Bootstrap 2',
        alt: 'bootstrap2',
        url: 'assets/kelas-22.png',
        link: 'class/2/2/',
        target: '_blank',
        rel: 'noopener noreferrer',
        content: 'Profil',
    },
    {
        title: 'Bootstrap 3',
        alt: 'bootstrap3',
        url: 'assets/kelas-23.png',
        link: 'class/2/3/',
        target: '_blank',
        rel: 'noopener noreferrer',
        content: 'Kontak',
    },
    {
        title: 'Bootstrap 4',
        alt: 'bootstrap4',
        url: 'assets/kelas-24.png',
        link: 'class/2/4/',
        target: '_blank',
        rel: 'noopener noreferrer',
        content: 'Navigasi Halaman',
    },
    {
        title: 'Bootstrap 5',
        alt: 'bootstrap5',
        url: 'assets/kelas-25.png',
        link: 'class/2/5/',
        target: '_blank',
        rel: 'noopener noreferrer',
        content: 'Carousel',
    },
    {
        title: 'Bootstrap 6',
        alt: 'bootstrap6',
        url: 'assets/kelas-26.png',
        link: 'class/2/6/',
        target: '_blank',
        rel: 'noopener noreferrer',
        content: 'Landing Page Webinar',
    },
    {
        title: 'Landing Page',
        alt: 'landingpage',
        url: 'assets/proyek-landing-page.png',
        link: 'project/1/',
        target: '_blank',
        rel: 'noopener noreferrer',
        content: 'Landing Page Kopi Papasan',
    },
    {
        title: 'Dashboard',
        alt: 'dashboard',
        url: 'assets/proyek-dashboard.png',
        link: 'project/2/',
        target: '_blank',
        rel: 'noopener noreferrer',
        content: 'Dashboard Admin Starline',
    },
    {
        title: 'Re-design',
        alt: 'redesign',
        url: 'assets/proyek-redesign.png',
        link: 'project/3/',
        target: '_blank',
        rel: 'noopener noreferrer',
        content: 'Re-desain Showreel Gamelab.id',
    },
];
